AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a Route 53 Private Hosted Zone for the Lab VPC

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: "VPC"
        Parameters:
          - MyVPC
      - Label: 
          default: "Region"
        Parameters:
          - MyRegion
      - Label:
          default: "DNS Zone"
        Parameters:
          - MyDnsZone

      - Label:
          default: "App Server IP Addresses"
        Parameters:
          - WorkloadAppIP1
          - WorkloadAppIP2
    
    ParameterLabels:
      MyVPC:
        default: "Select the VPC where the App Connector is deployed"
      MyRegion:
        default: "Select the Region where the App Connector is deployed"
      MyDnsZone:
        default: "Type an internal domain name for your DNS Zone"
      WorkloadAppIP1:
        default: "Type the private IP of App1 EC2"
      WorkloadAppIP2:
        default: "Type the private IP of App2 EC2"

Parameters:
  MyVPC:
    Description: >
      VPC for App Connector
    Type: 'AWS::EC2::VPC::Id'
  
  MyRegion:
    Description: >
      Region for App Connector
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-2
      - us-east-1
      - us-west-1
      - us-west-2
      - af-south-1
      - ap-east-1
      - ap-south-2
      - ap-southeast-3
      - ap-south-1
      - ap-northeast-3
      - ap-northeast-2
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-south-1
      - eu-west-3
      - eu-south-2
      - eu-north-1
      - eu-central-2
      - me-south-1
      - me-central-1
      - sa-east-1
      - us-gov-east-1
      - us-gov-west-1
    
  MyDnsZone:
    Description: > 
      Domain for DNS Zone
    Type: String
    
  WorkloadAppIP1:
    Description: > 
      IP Address of Workload 1 Application
    Type: String

  WorkloadAppIP2:
    Description: > 
      IP Address of Workload 1 Application
    Type: String

Resources:

  DNSZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'DNS Hosted Zone'
      Name: !Ref MyDnsZone
      VPCs: 
        - 
          VPCId: !Ref MyVPC
          VPCRegion: !Ref MyRegion

  DNSWorkloadApp1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${MyDnsZone}.'
      Name: !Sub 'app1.${MyDnsZone}'
      Type: A
      TTL: '300'
      ResourceRecords:
          - !Ref WorkloadAppIP1
    DependsOn: DNSZone

  DNSWorkloadApp2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${MyDnsZone}.'
      Name: !Sub 'app2.${MyDnsZone}'
      Type: A
      TTL: '300'
      ResourceRecords:
          - !Ref WorkloadAppIP2
    DependsOn: DNSZone